<?php
echo $this->tag->hiddenField(["idCarac", "value" => $carac->id]);
?>

<!-- Div pour les boutons -->
<div class="boutonsActionReferentiel">
    <div>
        <?php
        //Si Carac Primaires
        if ($carac->type == Caracteristiques::CARAC_PRIMAIRE) {
            if (Autorisations::hasAutorisation(Autorisations::GAMEPLAY_GESTION_CARAC_PRIMAIRE, $auth['autorisations'])) {
                echo Phalcon\Tag::SubmitButton(array("Modifier", 'id' => 'modifierCarac', 'class' => 'bouton', 'title' => "Permet de modifier la caractéristique."));
            }
        } else {
            if ((Autorisations::hasAutorisation(Autorisations::GAMEPLAY_CREATION_CARAC, $auth['autorisations']) && $carac->isModifiable)
              || Autorisations::hasAutorisation(Autorisations::GAMEPLAY_GESTION_CARAC_PRIMAIRE, $auth['autorisations'])) {
                echo Phalcon\Tag::SubmitButton(array("Modifier", 'id' => 'modifierCarac', 'class' => 'bouton', 'title' => "Permet de modifier la caractéristique."));
            }
        }
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Annuler", 'id' => 'annulerEditerCarac', 'class' => 'bouton', 'title' => "Permet de retourner vers la caractéristique."));
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Retour liste", 'id' => 'retourListeCarac', 'class' => 'bouton', 'title' => "Permet de retourner vers la liste des caractéristiques."));
        ?>
    </div>
</div>

<!-- Div pour la caractéristique -->
<div id="divGlobalCarac" class="divReferentiel">
    <!-- En-tête -->
    <div id="divEnteteReferentiel">
        <?php echo Phalcon\Tag::textField(array("titreFormCarac", "class" => "formulaireField titreEdition", "value" => $carac->nom)); ?>
    </div>

    <!-- div Contenu -->
    <div id="divContenuCarac" class="divContenuReferentiel">
        <!-- Image -->
        <div id="divImageCarac" class="imageCentreeEdition">
            <?php echo Phalcon\Tag::image([$carac->image, "class" => 'imageCarac', 'id' => 'imageCarac']); ?>
            <div id="listeImageCarac">
                <?php echo $carac->genererListeImageCarac(); ?>
            </div>
            <div id="divAjouterImageCrac">
                <?php
                echo Phalcon\Tag::textField(array("newImageCarac", "class" => "inputNouvelleImage", "value" => "Url de l'image"));
                echo Phalcon\Tag::SubmitButton(array("Charger", 'id' => 'chargerNewImageCarac', 'class' => 'bouton', 'title' => "Permet d'ajouter une image à partir d'une url."));
                ?>
            </div>
        </div>

        <!-- Description -->
        <div class="divDescriptionCaracEdition">
            <?php echo Fonctions::rawTextArea("descriptionCarac", str_replace("\n", "&#13;&#10;", $carac->description), "texteDescriptionReferentiel"); ?>
        </div>

        <div id="divInformationCaracEdition" class="divInformationCarac">

            <!-- Genre -->
            <div id="divGenreCarac" class="divContenuInformationReferentiel">
                <label for="genreCarac">Genre </label>
                <span id="genreCarac"><?php echo Constantes::genererSelectGenre($carac->genre, "selectGenreCarac"); ?></span>
            </div>

            <!-- Trigramme -->
            <div id="divTrigrammeCarac" class="divContenuInformationReferentiel">
                <label for="trigrammeCarac">Trigramme </label>
                <?php echo Phalcon\Tag::textField(array("trigrammeCarac", "class" => "formulaireField", "value" => $carac->trigramme, "size" => 3)); ?>
            </div>

            <!-- Type -->
            <div id="divTypeCarac" class="divContenuInformationReferentiel">
                <label for="typeCarac">Type </label>
                <span id="typeCarac"><?php echo $carac->genererListeType($auth); ?></span>
            </div>

            <!-- Valeur min -->
            <div id="divValMinCarac" class="divContenuInformationReferentiel">
                <label for="valMinCarac">Valeur minimum </label>
                <?php echo Phalcon\Tag::textField(array("valMinCarac", "class" => "formulaireField", "value" => $carac->valMin)); ?>
            </div>

            <!-- Valeur max -->
            <div id="divValMaxCarac" class="divContenuInformationReferentiel">
                <label for="valMaxCarac">Valeur maximum </label>
                <?php echo Phalcon\Tag::textField(array("valMaxCarac", "class" => "formulaireField", "value" => $carac->valMax)); ?>
            </div>

            <!-- Formule si Carac secondaire -->
            <?php if ($carac->type == Caracteristiques::CARAC_SECONDAIRE) { ?>
                <div id="divFormuleCarac" class="divContenuInformationReferentiel">
                    <label for="formuleCarac">Formule </label>
                    <span id="formuleCarac"><?php echo $carac->formule; ?></span>
                    <input type="button" class="boutonFormule" value="Changer formule"
                           onclick="afficherFormulaireFormule('formuleCarac');"
                           title="Permet d'ouvrir le formulaire afin de modifier la formule"/>
                </div>
            <?php } ?>


            <!-- Checkbox isModifiable - Uniquement pour les patrons -->
            <?php if (Autorisations::hasAutorisation(Autorisations::GAMEPLAY_GESTION_CARAC_PRIMAIRE, $auth['autorisations'])) { ?>
                <div id="divIsModifiableCarac" class="divContenuInformationReferentiel">
                    <?php
                    if ($carac->isModifiable) {
                        echo "<label for='isModifiableCarac'>Peut-être modifiée ? </label><input type='checkbox' id='isModifiableCarac' class='tickcrossFormulaireGameplay' checked/>";
                    } else {
                        echo "<label for='isModifiableCarac'>Peut-être modifiée ? </label><input type='checkbox' id='isModifiableCarac' class='tickcrossFormulaireGameplay'/>";
                    }
                    ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>