<?php
echo $this->tag->hiddenField(["idFamilleTalent", "value" => $famille->id]);
?>
<div class="popupTalent" id="popupFamilleTalent">
    <div class="entetePopupTalent" id="entetePopupFamilleTalent">
        <div class="divTitreTalent"><span class="titrePopup"><?php echo $famille->nom; ?></span></div>
    </div>

    <div class="formPopupTalent" id="formPopupFamille">
        <div class="divDataPopupTalent" id="blocCategorieFamille">
            <label for="categorieFamille">Catégorie </label>
            <span id="categorieFamille"><?php echo $famille->categorie->nom; ?></span>
        </div>

        <!-- Description -->
        <div class="divDataPopupTalent" id="blocCategorieFamille">
            <span id="descriptionFamilleTalent"><?php echo str_replace("\n", "<br/>", $famille->description); ?></span>
        </div>
    </div>

    <div class="boutonsActionPopupTalent" id="boutonsActionFamilleTalent">
        <div id="boutonEditerPopupTalentFamille" class="boutonActionPopupTalent">
            <?php echo Phalcon\Tag::SubmitButton(array("Editer", 'id' => 'editerFamilleTalent', 'class' => 'bouton', 'title' => "Permet d'accéder à l'écran de modification de la famille.")); ?>
        </div>

        <div id="boutonFermerPopupTalentFamille" class="boutonFermerPopupTalent">
            <?php echo Phalcon\Tag::SubmitButton(array("Fermer", 'id' => 'fermerPopupTalentFamille', 'class' => 'bouton', 'title' => "Permet de fermer la popup.")); ?>
        </div>
    </div>

    <div id="blocInformationsTechniquesTalentsContraintes">
        <!-- Bloc droit avec les différents blocs d'informations -->
        <div id="divInformationTechniqueFamille">
            <div>
                <div id="divBoutonsInformationsTechniques">
                    <?php
                    echo "<div class='divBoutonsContraintesTalent'>";
                    echo "<span class='libelleBoutonTechnique'>Contraintes </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteContraintesFamille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteContraintesFamille', 'class' => 'buttonHideGauche'));
                    echo "</div>";
                    ?>
                </div>
            </div>
        </div>
        <div id="informationTechniqueFamille" style="display:none"></div>
    </div>
</div>