<?php
echo $this->tag->hiddenField(["type", "value" => $type]);
echo $this->tag->hiddenField(["idType", "value" => $idType]);
echo $this->tag->hiddenField(["idContrainte", "value" => $contrainte->id]);
echo $this->tag->hiddenField(["position", "value" => $position]);
?>


<div id="contenuContrainte">
    <div id="enteteContrainte">
        <div id="divTitreContrainte"><span
                    class="titrePopup">Modifier la contrainte <?php echo $contrainte->nom; ?></span></div>
    </div>


    <div id="detailContrainte" class="detailElement">
        <?php echo $contrainte->genererDetailContrainte("edition", $type, $idType, $position); ?>
    </div>

    <div id="boutonModifierPopupContrainte" class="boutonActionPopupElement">
        <?php echo Phalcon\Tag::SubmitButton(array("Modifier", 'id' => 'modifierContrainte', 'class' => 'bouton modifierContrainte', 'title' => "Modifie les valeurs de la contrainte.")); ?>
    </div>

    <div id="boutonFermerPopupContrainte" class="boutonFermerPopupElement">
        <?php echo Phalcon\Tag::SubmitButton(array("Annuler", 'id' => 'annulerAjoutContrainte', 'class' => 'bouton annulerAjoutContrainte', 'title' => "Annule la modification de la contrainte.")); ?>
    </div>
</div>