<?php
echo $this->tag->hiddenField(["idCompetence", "value" => $competence->id]);
?>
<div class="contenuPopupCompetence" id="contenuPopupCompetence">
    <div class="entetePopupCompetence" id="entetePopupCompetence">
        <div class="divTitreCompetence">
            <?php echo Phalcon\Tag::textField(array("nomCompetence", "class" => "formulaireField titrePopupCompetence", "value" => $competence->nom)); ?>
        </div>
    </div>

    <div class="formPopupComptence" id="formPopupCompetence">
        <!-- On Affiche l'image à gauche -->
        <div class='divBlocImageCompetence' id='divBlocImageCompetence'>
            <div id="divImageCompetence">
                <?php echo Phalcon\Tag::image([$competence->image, "class" => 'imageCompetence', 'id' => 'imageCompetence']); ?>
            </div>
            <div id="divGestionImageCompetence">
                <div id="divListeImagesCompetence">
                    <?php echo $competence->genererListeImages(); ?>
                </div>
                <div id="divAjouterImageCompetence">
                    <?php
                    echo Phalcon\Tag::textField(array("newImageCompetence", "class" => "inputNouvelleImage", "value" => "Url de l'image"));
                    echo Phalcon\Tag::SubmitButton(array("Charger", 'id' => 'chargerNewImageCompetence', 'class' => 'bouton', 'title' => "Permet d'ajouter une image à partir d'une url."));
                    ?>
                </div>
            </div>
        </div>

        <div class="formCompetence" id="formCompetenceEdition">
            <!-- Description -->
            <div class="divTextePopupCompetence" id="divDescriptionPopupCompetence">
                <?php echo Fonctions::rawTextArea("descriptionCompetence", str_replace("\n", "&#13;&#10;", $competence->description), "texteDescriptionPopupCompetence"); ?>
            </div>

            <!-- Type -->
            <div class="divDataPopupCompetence" id="blocSelectTypeCompetence">
                <label for="selectTypeCompetence">Type </label>
                <span id="selectTypeCompetence"><?php echo $competence->getListeType(); ?></span>
            </div>

            <!-- Disponible en jeu -->
            <div id="divDisponibleCompetence" class="divDataPopupCompetence">
                <?php
                if ($competence->isActif) {
                    echo "<label for='isDispoCompetence'>Disponible en jeu ? </label><input type='checkbox' id='isDispoCompetence' class='tickcrossFormulaireGameplay' checked />";
                } else {
                    echo "<label for='isDispoCompetence'>Disponible en jeu ? </label><input type='checkbox' id='isDispoCompetence' class='tickcrossFormulaireGameplay' />";
                }
                ?>
            </div>

            <!-- Compétence activable -->
            <div id="divCompetenceActivalbe" class="divDataPopupCompetence">
                <label for='isCompetenceActivable'>Cette compétence doit elle être activée ? </label>
                <?php
                if ($competence->activable) {
                    echo "<input type='checkbox' id='isCompetenceActivable' class='tickcrossFormulaireGameplay' checked onClick='gererBlocActif();'/>";
                } else {
                    echo "<input type='checkbox' id='isCompetenceActivable' class='tickcrossFormulaireGameplay' onClick='gererBlocActif();'/>";
                }
                ?>
                <div class='divAide' id='divAideCompetenceActivable'
                     onMouseOver='afficherAide("Une compétence active recquiert de dépenser des PA pour être lancée. Une compétence passive, elle, ne le nécessite pas, mais peut, ou non, être entraînée.","divAideCompetenceActivable");'
                     onMouseOut='cacherAide();'></div>
            </div>

            <?php
            $style = "display:none;";
            if ($competence->activable) {
                $style = "display:block;";
            }
            ?>

            <!-- Bloc Activable -->
            <div id="divBlocActif" class="blocActifCompetence" style="<?php echo $style; ?>">
                <!-- MessageRP -->
                <div class="divTextePopupCompetence" id="divMessageRPPopupCompetence">
                    <?php echo Fonctions::rawTextArea("messageRPCompetence", str_replace("\n", "&#13;&#10;", $competence->messageRP), "texteMessageRPPopupCompetence"); ?>
                    <div class='divAide' id='divAideCompetenceMessageRP'
                         onMouseOver='afficherAide("Correspond au message qui s&#39;affichera sur le plateau de jeu lors de l&#39;utilisation de la compétence.","divAideCompetenceMessageRP");'
                         onMouseOut='cacherAide();'></div>
                </div>

                <!-- Evenement Lanceur -->
                <div class="divTextePopupCompetence" id="divEventLanceurPopupCompetence">
                    <?php echo Fonctions::rawTextArea("eventLanceurCompetence", str_replace("\n", "&#13;&#10;", $competence->evenementLanceur), "texteEventPopupCompetence"); ?>
                    <div class='divAide' id='divAideCompetenceEventLanceur'
                         onMouseOver='afficherAide("Correspond au message qui s&#39;affichera dans la liste des évenements du personnage ayant utilisé la compétence.","divAideCompetenceEventLanceur");'
                         onMouseOut='cacherAide();'></div>
                </div>

                <!-- Evenement Monde -->
                <div class="divTextePopupCompetence" id="divEventGlobalPopupCompetence">
                    <?php echo Fonctions::rawTextArea("eventGlobalCompetence", str_replace("\n", "&#13;&#10;", $competence->evenementGlobal), "texteEventPopupCompetence"); ?>
                    <div class='divAide' id='divAideCompetenceEventGlobal'
                         onMouseOver='afficherAide("Correspond au message qui s&#39;affichera dans la liste des évenements des personnages ayant observé l&#39;utilisation de la compétence. Ne rien mettre impliquera qu&#39;aucun évenement ne sera affiché.","divAideCompetenceEventGlobal");'
                         onMouseOut='cacherAide();'></div>
                </div>

                <!-- Cout en PA -->
                <div class="divDataPopupTalent">
                    <label for="coutPACompetence">Coût en PA </label>
                    <?php echo Phalcon\Tag::textField(array("coutPACompetence", "class" => "formulaireField", "value" => $competence->coutPA, "size" => 2)); ?>
                </div>

                <!-- Entrainable ?-->
                <div id="divEntrainableCompetence" class="divDataPopupCompetence">
                    <?php
                    if ($competence->isEntrainable) {
                        echo "<label for='isEntrainableCompetence'>Peut on entraîner la compétence ? </label><input type='checkbox' id='isEntrainableCompetence' class='tickcrossFormulaireGameplay' checked/>";
                    } else {
                        echo "<label for='isEntrainableCompetence'>Peut on entraîner la compétence ? </label><input type='checkbox' id='isEntrainableCompetence' class='tickcrossFormulaireGameplay'/>";
                    }
                    ?>
                    <div class='divAide' id='divAideCompetenceEntrainable'
                         onMouseOver='afficherAide("Affichera le bouton Entraîner sur la compétence. Ne rien mettre implique que cette compétence évoluera par d&#39;autres moyen que cette action (déplacement sur la carte, utilisation de techniques, etc...). Cocher la case permet également aux deux options d&#39;être disponibles.".","divAideCompetenceEntrainable");'
                         onMouseOut='cacherAide();'></div>
                </div>
            </div>

            <!-- Bloc Apprentissage -->
            <div id="divBlocApprentissageCompetence" class="blocApprentissageCompetence">
                <!-- Enseignable ?-->
                <div id="divEnseignableCompetence" class="divDataPopupCompetence">
                    <?php
                    if ($competence->isEnseignable) {
                        echo "<label for='isEnseignableCompetence'>Peut on enseigner la compétence ? </label><input type='checkbox' id='isEnseignableCompetence' class='tickcrossFormulaireGameplay' checked/>";
                    } else {
                        echo "<label for='isEnseignableCompetence'>Peut on enseigner la compétence ? </label><input type='checkbox' id='isEnseignableCompetence' class='tickcrossFormulaireGameplay'/>";
                    }
                    ?>
                </div>

                <!-- Rang à partir duquel il est possible d'auto-apprendre la compétence -->
                <div class="divDataPopupCompetence" id="blocSelectRangAutonomieCompetence">
                    <label for="selectRangAutonomie">Autonomie dans l'apprentissage de la compétence à partir
                        du </label>
                    <span id="selectRangAutonomie"><?php echo $competence->getListeRangAutonomie(); ?></span>
                    <div class='divAide' id='divAideCompetenceRangAutonomie'
                         onMouseOver='afficherAide("Détermine le rang à partir duquel la compétence peut être apprise ou entraînée seul.","divAideCompetenceRangAutonomie");'
                         onMouseOut='cacherAide();'></div>
                </div>
            </div>
        </div>
    </div>

    <div class="boutonsActionPopupCompetence" id="boutonsActionCompetence">
        <div id="boutonCreerPopupCompetence" class="boutonActionPopupCompetence">
            <?php echo Phalcon\Tag::SubmitButton(array("Modifier", 'id' => 'modifierCompetence', 'class' => 'bouton', 'title' => "Permet de modifier la compétence.")); ?>
        </div>

        <div id="boutonFermerPopupCompetence" class="boutonFermerPopupCompetence">
            <?php echo Phalcon\Tag::SubmitButton(array("Fermer", 'id' => 'fermerPopupCompetence', 'class' => 'bouton', 'title' => "Permet d'annuler la création de la compétence.")); ?>
        </div>
    </div>

    <div id="blocInformationsTechniquesCompetences">
        <!-- Bloc droit avec les différents blocs d'informations -->
        <div id="divInformationTechniqueCompetence">
            <div>
                <div id="divBoutonsInformationsTechniques">
                    <?php
                    echo "<div class='divBoutonsTechniquesCompetence'>";
                    echo "<span class='libelleBoutonTechnique'>Evolution </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteEvolutionCompetence', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteEvolutionCompetence', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesCompetence'>";
                    echo "<span class='libelleBoutonTechnique'>Effets </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteEffetCompetence', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteEffetCompetence', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesTalent'>";
                    echo "<span class='libelleBoutonTechnique'>Contraintes </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteContraintesCompetence', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteContraintesCompetence', 'class' => 'buttonHideGauche'));
                    echo "</div>";
                    ?>
                </div>
            </div>
        </div>
        <div id="informationTechnique" style="display:none"></div>
    </div>
</div>