<!-- En tete -->
<div class='entetePageAdministration'>
    <span class="titrePage">Administration</span>
</div>
<div id="texteIndex">
    <p>Depuis cette page vous avez accès aux différents outils d'administration de Lazarus. Ceux-ci concernent
        principalement la partie Role Play du jeu. En fonction de vos autorisations, vous pourrez intervenir sur
        certains des éléments suivants :</p>

    <p><span class='titrePetit'>L'onglet "Droits"</span> vous permet de gérer les différentes autorisations des groupes
        existant sur le jeu. Vous pouvez ainsi les consulter ou les modifier et créer de nouveaux groupes.</p>

    <p><span class='titrePetit'>L'onglet "Logs"</span> vous permet de consulter les différents logs du jeu. Toutes les
        actions effectuées par les joueurs, ou membre de la MAD, y sont enregistrées.</p>

    <p><span class='titrePetit'>L'onglet "Référentiels"</span> vous permet de gérer les différents référentiels RP du
        jeu. Vous pouvez consulter, ajouter ou modifier les races, les royaumes ou encore les panthéons et divinités,
        par exemple. C'est également à partir de cet onglet que vous pourrez définir, pour chaque référentiel, les
        questions à inclure au questionnaire d'inscription.</p>

    <p><span class='titrePetit'>L'onglet "Statistiques"</span> vous permet de consulter les différentes statistiques du
        jeu, en matière de fréquentation ou de participation, par exemple.</p>

    <p><span class='titrePetit'>L'onglet "Test"</span> vous permet de créer et d'utiliser un profil de Test afin de
        tester les différentes fonctionnalités et droits du jeu.</p>

    <p><span class='titrePetit'>L'onglet "Image"</span> vous permet de gérer le répertoire des images directement depuis
        votre navigateur.</p>

    <p><span class='titrePetit'>L'onglet "Gif"</span> vous permet de gérer le répertoire des gifs directement depuis
        votre navigateur.</p>
</div>
