<?php
echo $this->tag->hiddenField(["idVille", "value" => $ville->id]);
?>

<!-- Div pour les boutons -->
<div id="divBoutonsVilleConsultation" class="boutonsActionReferentiel">
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_FORMULAIRES_GERER, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Editer", 'id' => 'accesEditerVille', 'class' => 'bouton', 'title' => "Permet d'afficher le formulaire de la ville en modification."));
        }
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Retour", 'id' => 'retourListeVille', 'class' => 'bouton', 'title' => "Permet de retourner vers la liste des villes."));
        ?>
    </div>
</div>

<!-- Div pour la ville -->
<div id="divVille" class="divReferentiel">
    <!-- En-tête -->
    <div id="divEnteteReferentiel">
        <span id="titreVille" class="titreReferentiel"><?php echo $ville->nom; ?></span>
    </div>

    <!-- div Contenu -->
    <div id="divContenuVille" class="divContenuReferentiel">
        <!-- Image -->
        <div id="divImageVilleConsultation">
            <?php echo Phalcon\Tag::image([$ville->image, "class" => 'imageVilleConsultation', "id" => 'imageVille']); ?>
        </div>

        <!-- Description -->
        <div id="divDescriptionVille">
            <span id="descriptionVille"><?php echo str_replace("\n", "<br/>", $ville->description); ?></span>
        </div>

        <!-- Detail  -->
        <div id="divInformationVille" class="divInformationReferentiel">
            <!-- Article du wiki lié -->
            <div id="divArticleVille" class="divArticleReferentiel">
                <label for="articleVille">Article du wiki </label>
                <?php if ($ville->article != null && $ville->article) { ?>
                    <a href="#" id="articleVille"
                       onclick="openPopUpWiki(<?php echo $ville->idArticle; ?>)"><?php echo $ville->article->titre; ?></a>
                <?php } else { ?>
                    <span class="texte" id="articleVille">Aucun</span>
                <?php } ?>
            </div>

            <!-- Id Royaume Origine -->
            <div id="divRoyaumeOrigineVille" class="divContenuInformationReferentiel">
                <label for="royaumeOrigineVille">Royaume d'origine </label>
                <span id="royaumeOrigineVille"><?php echo $ville->royaumeOrigine->nom; ?></span>
                <div class='divAide' id='divAideRoyaumeOrigineVille'
                     onMouseOver='afficherAide("Il s&#39;agit du royaume auquel la ville était rattachée à l&#39;origine.","divAideRoyaumeOrigineVille");'
                     onMouseOut='cacherAide();'></div>
            </div>

            <!-- Id Royaume Actuel -->
            <div id="divRoyaumeActuelVille" class="divContenuInformationReferentiel">
                <label for="royaumeActuelVille">Royaume actuel </label>
                <span id="royaumeActuelVille"><?php echo $ville->royaumeActuel->nom; ?></span>
                <div class='divAide' id='divAideRoyaumeActuelVille'
                     onMouseOver='afficherAide("Il s&#39;agit du royaume auquel la ville est rattachée.","divAideRoyaumeActuelVille");'
                     onMouseOut='cacherAide();'></div>
            </div>

            <!-- Message d'accueil -->
            <div id="divRoyaumeActuelVilleConsultation" class="divContenuInformationReferentiel">
                <label for="messageAccueilVille">Message d'accueil </label>
                <span id="messageAccueilVille"><?php echo str_replace("\n", "<br/>", $ville->messageAccueil); ?></span>
                <div class='divAide' id='divAideMessageAccueilVille'
                     onMouseOver='afficherAide("Le message d&#39;accueil s&#39;affiche lorsque le joueur entre en ville.","divAideMessageAccueilVille");'
                     onMouseOut='cacherAide();'></div>
            </div>

            <!-- Disponible en choix de naissance -->
            <div id="divIsNaissanceVille" class="divContenuInformationReferentiel">
                <?php
                if ($ville->isNaissance) {
                    echo "<label for='isNaissanceVille'>Disponible en choix de naissance ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isNaissanceVille"]);
                } else {
                    echo "<label for='isNaissanceVille'>Disponible en choix de naissance ?  </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isNaissanceVille"]);
                }
                ?>
            </div>

            <!-- Position sur la carte -->
            <div id="divPositionCarteVille" class="divContenuInformationReferentiel">
                <!-- Xmin/Xmax -->
                <div id="divPositionXVille" class="divContenuInformationReferentiel">
                    <label for="positionXMinVille">Abscisse entre </label>
                    <span id="positionXMinVille" class='positionVille'><?php echo $ville->xMin; ?></span>
                    <span id="separateurET"> et </span>
                    <span id="positionXmaxVille" class='positionVille'><?php echo $ville->xMax; ?></span>
                </div>

                <!-- Ymin/Ymax -->
                <div id="divPositionYVille" class="divContenuInformationReferentiel">
                    <label for="positionYMinVille">Ordonnée entre </label>
                    <span id="positionYMinVille" class='positionVille'><?php echo $ville->yMin; ?></span>
                    <span id="separateurET"> et </span>
                    <span id="positionXmaxVille" class='positionVille'><?php echo $ville->yMax; ?></span>
                </div>
            </div>
        </div>
    </div>

    <div id="blocInformationsTechniques">
        <!-- Bloc droit avec les différents blocs d'informations -->
        <div id="divInformationTechniqueVille">
            <div>
                <div id="divBoutonsInformationsTechniques">
                    <?php
                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Gestion </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteGestionVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteGestionVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Finance </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteFinanceVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteFinanceVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Diplomatie </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteDiplomatieVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteDiplomatieVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Milice </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteMiliceVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteMiliceVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Quartiers </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteQuartierVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteQuartierVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";
                    ?>
                </div>
            </div>
        </div>
        <div id="informationTechnique" style="display:none"></div>
    </div>
</div>