<?php
echo $this->tag->hiddenField(["idDieu", "value" => $dieu->id]);
?>

<!-- Div pour les boutons -->
<div id="divBoutonsDieuConsultation" class="boutonsActionReferentiel">
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_FORMULAIRES_GERER, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Editer", 'id' => 'editerDieu', 'class' => 'bouton', 'title' => "Permet d'afficher le formulaire du dieu en modification."));
        }
        ?>
    </div>
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_QUESTIONNAIRE_INSCRIPTION_CONSULTATION, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Questionnaires", 'id' => 'consulterQuestionnaireInscriptionDivinite', 'class' => 'bouton', 'title' => "Permet d'afficher le questionnaire lié à cette race."));
        }
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Retour", 'id' => 'retourListeDieu', 'class' => 'bouton', 'title' => "Permet de retourner vers la liste des divinités."));
        ?>
    </div>
</div>

<!-- Div pour le dieu -->
<div id="divDieu" class="divReferentiel">
    <!-- En-tête -->
    <div id="divEnteteReferentiel">
        <span id="titreDieu" class="titreReferentiel"><?php echo $dieu->nom; ?></span>
    </div>

    <!-- div Contenu -->
    <div id="divContenuDieu" class="divContenuReferentiel">
        <!-- Image -->
        <div id="divImageDieuConsultation">
            <?php echo Phalcon\Tag::image([$dieu->img, "class" => 'imgDieuConsultation']); ?>
        </div>

        <!-- Description -->
        <div id="divDescriptionDieuConsultation">
            <span id="descriptionDieuConsultation"><?php echo str_replace("\n", "<br/>", $dieu->description); ?></span>
        </div>
        <!-- Detail  -->
        <div id="divInformationDieuConsultation" class="divInformationReferentiel">
            <!-- Article du wiki lié -->
            <div id="divArticleDieuConsultation" class="divArticleReferentiel">
                <label for="articleDieuConsultation">Article du wiki </label>
                <?php if ($dieu->article != null && $dieu->article) { ?>
                    <a href="#" id="articleDieuConsultation"
                       onclick="openPopUpWiki(<?php echo $dieu->idArticle; ?>)"><?php echo $dieu->article->titre; ?></a>
                <?php } else { ?>
                    <span class="texte" id="articleDieuConsultation">Aucun</span>
                <?php } ?>
            </div>

            <!-- Couleur -->
            <div id="divCouleurDieuConsultation" class="divContenuInformationReferentiel">
                <label for="couleurDieuConsultation">Couleur </label>
                <span id="couleurDieuConsultation" class="couleurCarre"><?php echo $dieu->couleur; ?></span>
                <span id="carreCouleurDieu" style="background-color:<?php echo $dieu->couleur; ?>" class="carreCouleur">&nbsp;&nbsp;</span>
            </div>

            <!-- Disponible à l'inscription -->
            <div id="divInscriptionDieuConsultation" class="divContenuInformationReferentiel">
                <?php
                if ($dieu->isDispoInscription) {
                    echo "<label for='isDispoInscriptionDieuConsultation'>Disponible à l'inscription ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isDispoInscriptionDieuConsultation"]);
                } else {
                    echo "<label for='isDispoInscriptionDieuConsultation'>Disponible à l'incsription ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isDispoInscriptionDieuConsultation"]);
                }
                ?>
            </div>

            <!-- Race du dieu -->
            <div id="divRaceDieuConsultation" class="divContenuInformationReferentiel">
                <label for="raceDieuConsultation">Race </label>
                <span id="raceDieuConsultation"><?php echo $dieu->race->nom; ?></span>
            </div>
        </div>
    </div>

    <!-- div Autorisations -->
    <div id="divAutorisationsDieu" class="divAutorisationReferentiel">
        <!-- Religion -->
        <div id="divAutorisationDieuReligionConsultation" class="divContenuAutoriseReferentiel">
            <?php if ($dieu->idReligion != 0) { ?>
                <label for="religionDieuConsultation">Ce dieu appartient à la religion </label>
                <span id="religionDieuConsultation"
                      class="contenuAutorisationReferentiel"><?php echo $dieu->religion->nom; ?></span>
            <?php } else { ?>
                <span id="religionDieuConsultation" class="contenuAutorisationReferentiel">Ce dieu ne fait partie d'aucune religion (Donc il sert à rien !).</span>
            <?php } ?>
        </div>
    </div>
</div>