<?php
echo $this->tag->hiddenField(["idRoyaume", "value" => $royaume->id]);
?>

<!-- Div pour les boutons -->
<div id="divBoutonsRoyaumeConsultation" class="boutonsActionReferentiel">
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_FORMULAIRES_GERER, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Editer", 'id' => 'editerRoyaume', 'class' => 'bouton', 'title' => "Permet d'afficher le formulaire du royaume en modification."));
        }
        ?>
    </div>
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_QUESTIONNAIRE_INSCRIPTION_CONSULTATION, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Questionnaire", 'id' => 'consulterQuestionnaireInscriptionRoyaume', 'class' => 'bouton', 'title' => "Permet d'afficher le questionnaire lié à ce royaume."));
        }
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Retour", 'id' => 'retourListeRoyaume', 'class' => 'bouton', 'title' => "Permet de retourner vers la liste des royaumes."));
        ?>
    </div>
</div>

<!-- Div pour le royaume -->
<div id="divRoyaume" class="divReferentiel">
    <!-- En-tête -->
    <div id="divEnteteReferentiel">
        <span id="titreRoyaume" class="titreReferentiel"><?php echo $royaume->nom; ?></span>
    </div>

    <!-- div Contenu -->
    <div id="divContenuRoyaume" class="divContenuReferentiel">
        <!-- Etendard -->
        <div id="divEtendardRoyaumeConsultation">
            <?php echo Phalcon\Tag::image([$royaume->etendard, "class" => 'etendardRoyaumeConsultation']); ?>
        </div>

        <!-- Description -->
        <div id="divDescriptionRoyaumeConsultation">
            <span id="descriptionRoyaumeConsultation"><?php echo str_replace("\n", "<br/>", $royaume->description); ?></span>
        </div>

        <div id="divInformationRoyaumeConsultation" class="divInformationReferentiel">
            <!-- Article du wiki lié -->
            <div id="divArticleRoyaumeConsultation" class="divArticleReferentiel">
                <label for="articleRoyaumeConsultation">Article du wiki </label>
                <?php if ($royaume->article != null && $royaume->article) { ?>
                    <a href="#" id="articleRoyaumeConsultation"
                       onclick="openPopUpWiki(<?php echo $royaume->idArticle; ?>)"><?php echo $royaume->article->titre; ?></a>
                <?php } else { ?>
                    <span class="texte" id="articleRoyaumeConsultation">Aucun</span>
                <?php } ?>
            </div>

            <!-- Couleur -->
            <div id="divCouleurRoyaumeConsultation" class="divContenuInformationReferentiel">
                <label for="couleurRoyaumeConsultation">Couleur </label>
                <span id="couleurRoyaumeConsultation" class="couleurCarre"><?php echo $royaume->couleur; ?></span>
                <div id="carreCouleurRoyaume" style="background-color:<?php echo $royaume->couleur; ?>"
                     class='carreCouleur'></div>
            </div>

            <!-- Disponible à l'inscription -->
            <div id="divInscriptionRoyaumeConsultation" class="divContenuInformationReferentiel">
                <?php
                if ($royaume->isDispoInscription) {
                    echo "<label for='isDispoInscriptionRoyaumeConsultation'>Disponible à l'inscription ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isDispoInscriptionRoyaumeConsultation"]);
                } else {
                    echo "<label for='isDispoInscriptionRoyaumeConsultation'>Disponible à l'incsription ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isDispoInscriptionRoyaumeConsultation"]);
                }
                ?>
            </div>
        </div>
    </div>

    <!-- div Autorisations -->
    <div id="divAutorisationsRoyaume" class="divAutorisationReferentiel">
        <!-- Religion -->
        <div id="divAutorisationRoyaumeReligionConsultation" class="divContenuAutoriseReferentiel">
            <label for="religionAutoriseeRoyaumeConsultation">Religions jouables dans le royaume </label>
            <span id="religionAutoriseeRoyaumeConsultation"
                  class="contenuAutorisationReferentiel"><?php echo $royaume->genererReligionsAutorisees("consultation"); ?></span>
        </div>

        <!-- Race -->
        <div id="divAutorisationRoyaumeRaceConsultation" class="divContenuAutoriseReferentiel">
            <label for="raceAutoriseeRoyaumeConsultation">Races jouables dans le royaume </label>
            <span id="raceAutoriseeRoyaumeConsultation"
                  class="contenuAutorisationReferentiel"><?php echo $royaume->genererRacesAutorisees("consultation"); ?></span>
        </div>
    </div>

    <div id="blocInformationsTechniques">
        <!-- Bloc droit avec les différents blocs d'informations -->
        <div id="divInformationTechniqueRoyaume">
            <div>
                <div id="divBoutonsInformationsTechniques">
                    <?php
                    echo "<div class='divBoutonsTechniquesRoyaume'>";
                    echo "<span class='libelleBoutonTechnique'>Bonus Inscription</span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteBonusRoyaume', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteBonusRoyaume', 'class' => 'buttonHideGauche'));
                    echo "</div>";
                    ?>
                </div>
            </div>
        </div>
        <div id="informationTechnique" style="display:none"></div>
    </div>
</div>
