<?php
echo $this->tag->hiddenField(["idRace", "value" => $race->id]);
?>

<!-- Div pour les boutons -->
<div id="divBoutonsRaceConsultation" class="boutonsActionReferentiel">
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_FORMULAIRES_GERER, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Editer", 'id' => 'editerRace', 'class' => 'bouton', 'title' => "Permet d'afficher le formulaire de la race en modification."));
        }
        ?>
    </div>
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_QUESTIONNAIRE_INSCRIPTION_CONSULTATION, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Questionnaires", 'id' => 'consulterQuestionnaireInscriptionRace', 'class' => 'bouton', 'title' => "Permet d'afficher le questionnaire lié à cette race."));
        }
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Retour", 'id' => 'retourListeRace', 'class' => 'bouton', 'title' => "Permet de retourner vers la liste des races."));
        ?>
    </div>
</div>

<!-- Div pour la race -->
<div id="divRace" class="divReferentiel">
    <!-- En-tête -->
    <div id="divEnteteReferentiel">
        <span id="titreRace" class="titreReferentiel"><?php echo $race->nom; ?></span>
    </div>

    <!-- div Contenu -->
    <div id="divContenuRace" class="divContenuReferentiel">
        <!-- Image -->
        <div id="divImageRaceConsultation">
            <?php echo Phalcon\Tag::image([$race->image, "class" => 'imageRaceConsultation']); ?>
        </div>

        <!-- Description -->
        <div id="divDescriptionRaceConsultation">
            <span id="descriptionRaceConsultation"><?php echo str_replace("\n", "<br/>", $race->description); ?></span>
        </div>

        <!-- Detail  -->
        <div id="divInformationRaceConsultation" class="divInformationReferentiel">
            <!-- Article du wiki lié -->
            <div id="divArticleRaceConsultation" class="divArticleReferentiel">
                <label for="articleRaceConsultation">Article du wiki </label>
                <?php if ($race->article != null && $race->article) { ?>
                    <a href="#" id="articleRaceConsultation"
                       onclick="openPopUpWiki(<?php echo $race->idArticle; ?>)"><?php echo $race->article->titre; ?></a>
                <?php } else { ?>
                    <span class="texte" id="articleRaceConsultation">Aucun</span>
                <?php } ?>
            </div>

            <!-- Disponible à l'inscription -->
            <div id="divInscriptionRaceConsultation" class="divContenuInformationReferentiel">
                <?php
                if ($race->isDispoInscription) {
                    echo "<label for='isDispoInscriptionRaceConsultation'>Disponible à l'inscription ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isDispoInscriptionRaceConsultation"]);
                } else {
                    echo "<label for='isDispoInscriptionRaceConsultation'>Disponible à l'incsription ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaireAdministration', "id" => "isDispoInscriptionRaceConsultation"]);
                }
                ?>
            </div>

            <!-- Contraintes physiques liés à la race -->
            <div id="divContraintesPhysiques" class="divContenuInformationReferentiel">
                <div id="divRaceTaille">
                    <label for="raceTailleMin">Taille (cm) entre </label>
                    <span id="raceTailleMin"><?php echo $race->tailleMin; ?></span>
                    <label for="raceTailleMax"> et </label>
                    <span id="raceTailleMax"><?php echo $race->tailleMax; ?></span>
                </div>
                <div id="divRacePoids">
                    <label for="racePoidsMin">Poids (kg) entre </label>
                    <span id="racePoidsMin"><?php echo $race->poidsMin; ?></span>
                    <label for="racePoidsMax"> et </label>
                    <span id="racePoidsMax"><?php echo $race->poidsMax; ?></span>
                </div>
                <div id="divRaceAge">
                    <label for="raceAgeMin">Âge (cycles) entre </label>
                    <span id="raceAgeMin"><?php echo $race->ageMin; ?></span>
                    <label for="raceAgeMax"> et </label>
                    <span id="raceAgeMax"><?php echo $race->ageMax; ?></span>
                </div>
                <div id="divRaceYeux">
                    <label for="listeYeux">Couleur des yeux autorisés </label>
                    <span id="listeYeux" class="texte"><?php echo $race->yeuxAutorise; ?></span>
                </div>
                <div id="divRaceCheveux">
                    <label for="listeCheveux">Couleur des cheveux autorisés </label>
                    <span id="listeCheveux" class="texte"><?php echo $race->cheveuxAutorise; ?></span>
                </div>
            </div>
        </div>
    </div>
    <!-- div Autorisations -->
    <div id="divAutorisationsRace" class="divAutorisationReferentiel">
        <!-- Royaume -->
        <div id="divRaceAutoriseeRoyaume" class="divContenuAutoriseReferentiel">
            <label for="raceAutoriseeRoyaume">Cette race peut être jouée, à l'inscription, dans les royaumes : </label>
            <span id="raceAutoriseeRoyaume"
                  class="contenuAutorisationReferentiel"><?php echo $race->genererPresenceRoyaume(); ?></span>
        </div>

        <!-- Religion -->
        <div id="divAutorisationRaceReligionConsultation" class="divContenuAutoriseReferentiel">
            <label for="religionAutoriseeRaceConsultation">Religions jouables pour cette race </label>
            <span id="religionAutoriseeRaceConsultation"
                  class="contenuAutorisationReferentiel"><?php echo $race->genererReligionsAutorisees("consultation"); ?></span>
        </div>
    </div>

    <div id="blocInformationsTechniques">
        <!-- Bloc droit avec les différents blocs d'informations -->
        <div id="divInformationTechniqueRace">
            <div>
                <div id="divBoutonsInformationsTechniques">
                    <?php
                    echo "<div class='divBoutonsTechniquesReligion'>";
                    echo "<span class='libelleBoutonTechnique'>Bonus Inscription</span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteBonusRace', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteBonusRace', 'class' => 'buttonHideGauche'));
                    echo "</div>";
                    ?>
                </div>
            </div>
        </div>
        <div id="informationTechnique" style="display:none"></div>
    </div>
</div>