<?php
echo $this->tag->hiddenField(["idVille", "value" => $ville->id]);
echo $this->tag->hiddenField(["hasCarte", "value" => $ville->hasCarte()]);
?>
<!-- Div pour les boutons -->
<div id="divBoutonsVilleEdition" class="boutonsActionReferentiel">
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::GAMEPLAY_GESTION_MAGIE_MODIFIER, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Modifier", 'id' => 'modifierVille', 'class' => 'bouton', 'title' => "Modifier la ville."));
        }
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Annuler", 'id' => 'annulerEditerVille', 'class' => 'bouton', 'title' => "Permet de retourner à la ville."));
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Retour", 'id' => 'retourListeVille', 'class' => 'bouton', 'title' => "Permet de retourner à la liste des Villes."));
        ?>
    </div>
</div>

<!-- Div pour la ville -->
<div id="divVille" class="divReferentiel">
    <!-- En-tête -->
    <div id="divEnteteReferentiel">
        <?php echo Phalcon\Tag::textField(array("nomVille", "class" => "formulaireField titreEdition", "value" => $ville->nom)); ?>
    </div>

    <!-- div Contenu -->
    <div id="divContenuVille" class="divContenuReferentiel">
        <!-- Image -->
        <div id="divImageVille">
            <?php echo Phalcon\Tag::image([$ville->image, "class" => 'imageVille', 'id' => 'imageVille']); ?>
            <div id="listeImageVille">
                <?php echo $ville->genererListeImage(); ?>
            </div>
            <div id="divAjouterImageVille">
                <?php
                echo Phalcon\Tag::textField(array("newImageVille", "class" => "inputNouvelleImage", "value" => "Url de l'image"));
                echo Phalcon\Tag::SubmitButton(array("Charger", 'id' => 'chargerNewImageVille', 'class' => 'bouton', 'title' => "Permet d'ajouter une image à partir d'une url."));
                ?>
            </div>
        </div>
    </div>

    <!-- Description -->
    <div id="divDescriptionVille">
        <?php echo Fonctions::rawTextArea("descriptionVille", str_replace("\n", "&#13;&#10;", $ville->description), "texteDescriptionVilleReferentiel"); ?>
    </div>

    <!-- Detail  -->
    <div id="divInformationVille" class="divInformationReferentiel">
        <!-- Article du wiki lié -->
        <div id="divArticleVille" class="divArticleReferentiel">
            <div id="autocompleteVilleWiki">
                <label for="s">Article du wiki </label>
                <?php
                if ($ville->article != null) {
                    echo Phalcon\Tag::textField(array("s", "class" => "field", "value" => $ville->article->titre));
                } else {
                    echo Phalcon\Tag::textField(array("s", "class" => "field"));
                }
                ?>
                <div id="suggestions"></div>
            </div>
        </div>

        <!-- Id Royaume Origine -->
        <div id="divRoyaumeOrigineVille" class="divContenuInformationReferentiel">
            <label for="royaumeOrigineVille">Royaume d'origine </label>
            <span id="royaumeOrigineVille"><?php echo $ville->getSelectRoyaume('royaumeOrigine'); ?></span>
            <div class='divAide' id='divAideRoyaumeOrigineVille'
                 onMouseOver='afficherAide("Il s&#39;agit du royaume auquel la ville était rattachée à l&#39;origine.","divAideRoyaumeOrigineVille");'
                 onMouseOut='cacherAide();'></div>
        </div>

        <!-- Id Royaume Actuel -->
        <div id="divRoyaumeActuelVille" class="divContenuInformationReferentiel">
            <label for="royaumeActuelVille">Royaume actuel </label>
            <span id="royaumeActuelVille"><?php echo $ville->getSelectRoyaume('royaumeActuel'); ?></span>
            <div class='divAide' id='divAideRoyaumeActuelVille'
                 onMouseOver='afficherAide("Il s&#39;agit du royaume auquel la ville est rattachée.","divAideRoyaumeActuelVille");'
                 onMouseOut='cacherAide();'></div>
        </div>

        <!-- Message d'accueil -->
        <div id="divRoyaumeActuelVilleConsultation" class="divContenuInformationReferentiel">
            <label for="messageAccueilVille">Message d'accueil </label>
            <?php echo Fonctions::rawTextArea("messageAccueilVille", str_replace("\n", "&#13;&#10;", $ville->messageAccueil), "texteDescriptionMessageReferentiel"); ?>
            <div class='divAide' id='divAideMessageAccueilVille'
                 onMouseOver='afficherAide("Le message d&#39;accueil s&#39;affiche lorsque le joueur entre en ville.","divAideMessageAccueilVille");'
                 onMouseOut='cacherAide();'></div>
        </div>

        <!-- Disponible en choix de naissance -->
        <div id="divIsNaissanceVille" class="divContenuInformationReferentiel">
            <?php
            if ($ville->isNaissance) {
                echo "<label for='isNaissanceVille'>Disponible en choix de naissance ? </label><input type='checkbox' id='isNaissanceVille' class='tickcrossFormulaireAdministration' checked />";
            } else {
                echo "<label for='isNaissanceVille'>Disponible en choix de naissance ? </label><input type='checkbox' id='isNaissanceVille' class='tickcrossFormulaireAdministration' />";
            }
            ?>
        </div>

        <!-- Position sur la carte -->
        <div id="divPositionCarteVille" class="divContenuInformationReferentiel">
            <?php if ($ville->hasCarte()) { ?>
                <!-- Xmin/Xmax -->
                <div id="divPositionXVille" class="divContenuInformationReferentiel">
                    <label for="positionXMinVille">Abscisse entre </label>
                    <input type='text' size=5 id="positionXMinVille" class='positionVille' value='0'>
                    <span id="separateurET"> et </span>
                    <input type='text' size=5 id="positionXMaxVille" class='positionVille' value='0'>
                </div>

                <!-- Ymin/Ymax -->
                <div id="divPositionYVille" class="divContenuInformationReferentiel">
                    <label for="positionYMinVille">Ordonnée entre </label>
                    <input type='text' size=5 id="positionYMinVille" class='positionVille' value='0'>
                    <span id="separateurET"> et </span>
                    <input type='text' size=5 id="positionYMaxVille" class='positionVille' value='0'>
                </div>
            <?php } else { ?>
                <!-- Xmin/Xmax -->
                <div id="divPositionXVille" class="divContenuInformationReferentiel">
                    <label for="positionXMinVille">Abscisse entre </label>
                    <span id="positionXMinVille" class='positionVille'><?php echo $ville->xMin; ?></span>
                    <span id="separateurET"> et </span>
                    <span id="positionXMaxVille" class='positionVille'><?php echo $ville->xMax; ?></span>
                </div>

                <!-- Ymin/Ymax -->
                <div id="divPositionYVille" class="divContenuInformationReferentiel">
                    <label for="positionYMinVille">Ordonnée entre </label>
                    <span id="positionYMinVille" class='positionVille'><?php echo $ville->yMin; ?></span>
                    <span id="separateurET"> et </span>
                    <span id="positionYMaxVille" class='positionVille'><?php echo $ville->yMax; ?></span>
                </div>
            <?php } ?>

            <div class='divAide' id='divAideDispositionVille'
                 onMouseOver='afficherAide("Si votre ville se trouve sur la carte principale, alors il faut renseigner les coordonnées. Sinon, laissez 0 pour chaque coordonnées puis rendez-vous dans l&#39;onglet Carte de la partie Gameplay et associez la carte correspondante à cette ville.","divAideDispositionVille");'
                 onMouseOut='cacherAide();'></div>
        </div>
    </div>


    <div id="blocInformationsTechniques">
        <!-- Bloc droit avec les différents blocs d'informations -->
        <div id="divInformationTechniqueVille">
            <div>
                <div id="divBoutonsInformationsTechniques">
                    <?php
                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Gestion </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteGestionVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteGestionVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Finance </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteFinanceVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteFinanceVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Diplomatie </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteDiplomatieVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteDiplomatieVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Milice </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteMiliceVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteMiliceVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesVille'>";
                    echo "<span class='libelleBoutonTechnique'>Quartiers </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteQuartierVille', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteQuartierVille', 'class' => 'buttonHideGauche'));
                    echo "</div>";
                    ?>
                </div>
            </div>
        </div>
        <div id="informationTechnique" style="display:none"></div>
    </div>
</div>