<?php if (Autorisations::hasAutorisation(Autorisations::ADMINISTRATION_FORMULAIRES_GERER, $auth['autorisations'])) { ?>
    <div class="divBoutonAjouterReferentiel">
        <?php echo Phalcon\Tag::SubmitButton(array("Ajouter", 'id' => 'boutonAjouterRoyaume', 'class' => 'bouton', 'title' => "Permet d'accéder au formulaire de création d'un royaume.")); ?>
    </div>
<?php } ?>
<?php
$listeRoyaumes = Royaumes::find();
if (count($listeRoyaumes) > 0) {
    echo "<table id='referentielRoyaume' class='referentielAdministration'>";
    echo "<tr>";
    echo "<th style='width:20%'></th>";
    echo "<th style='width:20%'>Nom</th>";
    echo "<th style='width:15%'>Jouable</th>";
    echo "<th style='width:45%'>Description</th>";
    echo "</tr>";
    foreach ($listeRoyaumes as $royaume) {
        echo "<tr class='ligneRoyaume' onclick='afficherDetailRoyaume(" . $royaume->id . ");' style='background-color:" . $royaume->couleur . "'>";
        echo "<td>" . Phalcon\Tag::image([$royaume->etendard, "class" => 'etendardRoyaumeReferentiel']) . "</td>";
        echo "<td><span class='nomListeReferentiel'>" . $royaume->nom . "</span></td>";
        if ($royaume->isDispoInscription) {
            echo "<td>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross']) . "</td>";
        } else {
            echo "<td>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross']) . "</td>";
        }
        echo "<td><span class='descriptionReferentielAdministration'>" . str_replace("\n", "<br/><br/>", $royaume->resumeDescription()) . "</span></td>";
        echo "</tr>";
    }
    echo "</table>";
} else {
    echo "<span class='resultatVide'>Il n'y a aucun royaume à afficher.</span>";
}
?>