<?php
echo $this->tag->hiddenField(["type", "value" => $type]);
echo $this->tag->hiddenField(["idType", "value" => $idType]);
echo $this->tag->hiddenField(["idEffet", "value" => $effet->id]);
echo $this->tag->hiddenField(["position", "value" => $position]);
?>


<div id="contenuEffet">
    <div id="enteteEffet">
        <div id="divTitreEffet"><span class="titrePopup">Modifier l'effet <?php echo $effet->nom; ?></span></div>
    </div>


    <div id="detailEffet" class="detailElement">
        <?php echo $effet->genererDetailEffet("edition", $type, $idType, $position); ?>
    </div>

    <div id="boutonModifierPopupEffet" class="boutonActionPopupElement">
        <?php echo Phalcon\Tag::SubmitButton(array("Modifier", 'id' => 'modifierEffet', 'class' => 'bouton', 'title' => "Modifie les valeurs de l'effet.")); ?>
    </div>

    <div id="boutonFermerPopupEffet" class="boutonFermerPopupElement">
        <?php echo Phalcon\Tag::SubmitButton(array("Annuler", 'id' => 'annulerAjoutEffet', 'class' => 'bouton', 'title' => "Annule la modification de l'effet.")); ?>
    </div>
</div>