<?php echo $this->tag->hiddenField(["gestionMagieSelect", "value" => "type"]); ?>
<!-- En tete -->
<div class='entetePageGameplay'>
    <span class="titrePage">Gestion de la Magie</span>
</div>

<!-- Liste des référentiel en accès -->
<div id="divAccesGestionMagie">
    <span class=""><?php echo Phalcon\Tag::SubmitButton(array("Types de magie", 'id' => 'boutonTypesMagie', 'class' => 'boutonGestionMagie boutonGestionMagieSelect', 'title' => "Permet d'afficher la liste de types de magie.")); ?></span>
    <span class=""><?php echo Phalcon\Tag::SubmitButton(array("Ecoles", 'id' => 'boutonEcolesMagie', 'class' => 'boutonGestionMagie', 'title' => "Permet d'afficher la liste des écoles.")); ?></span>
    <span class=""><?php echo Phalcon\Tag::SubmitButton(array("Sorts", 'id' => 'boutonSortsMagie', 'class' => 'boutonGestionMagie', 'title' => "Permet d'afficher la liste des sorts.")); ?></span>
</div>

<!-- Div pour la liste résumé -->
<div id="divListeResume">
    <?php echo $this->partial('gameplay/formulaire/magie/listeTypesMagie'); ?>
</div>

<!-- Div pour le referentiel en Consultation -->
<div id="divDetailConsultationReferentiel" class="divDetailReferentiel" style="display:none"></div>

<!-- Div pour le réferentiel en edition ou creation -->
<div id="divDetailEditionReferentiel" class="divDetailReferentiel" style="display:none"></div>