<!-- En tete -->
<div class='entetePageGameplay'>
    <span class="titrePage">Gestion des Textures</span>
</div>


<!-- Div pour la liste résumé -->
<div id="divListeResume">
    <?php echo $this->partial('gameplay/formulaire/textures/listeTextures'); ?>
</div>

<!-- Div pour le referentiel en Consultation -->
<div id="divDetailConsultationReferentiel" class="divDetailReferentiel" style="display:none"></div>

<!-- Div pour le réferentiel en edition ou creation -->
<div id="divDetailEditionReferentiel" class="divDetailReferentiel" style="display:none"></div>