<!-- En tete -->
<div class='entetePageGameplay'>
    <span class="titrePage">Gestion du Gameplay d'Idéo</span>
</div>
<div id="texteIndex">
    <p>Depuis cette page vous avez accès aux différents outils permettant de gérer les éléments gameplay d'Idéo. En
        fonction de vos autorisations, vous pourrez intervenir sur certains des éléments suivants :</p>

    <p><span class='titrePetit'>L'onglet "Cartes"</span> permet de gérer les différentes cartes du jeu.</p>

    <p><span class='titrePetit'>L'onglet "Terrains"</span> vous permet de consulter et gérer les différents types de
        terrains présents dans le jeu.</p>

    <p><span class='titrePetit'>L'onglet "Textures"</span> vous permet de consulter et gérer les différents types de
        textures présentes dans le jeu.</p>

    <p><span class='titrePetit'>L'onglet "Caracs"</span> vous permet de gérer, créer et modifier les caractéristiques
        présentes dans le jeu. Il convient de faire particulièrement attention avec ces éléments.</p>

    <p><span class='titrePetit'>L'onglet "Magie"</span> présente les différentes formes de magie, les écoles associées
        et les sortilèges qui les composent.</p>

    <p><span class='titrePetit'>L'onglet "Talents"</span> permet la gestion des différents arbres de talents du jeu.</p>

    <p><span class='titrePetit'>L'onglet "Compétences"</span> permet la gestion des différentes compétences du jeu.</p>

    <p><span class='titrePetit'>L'onglet "Equipement"</span> permet la gestion des différents équipements présent dans
        le jeu.</p>

    <p><span class='titrePetit'>L'onglet "Créatures"</span> permet la gestion des différentes créatures du jeu.</p>
</div>