<?php
echo $this->tag->hiddenField(["idSort", "value" => $sort->id]);
?>

<!-- Div pour les boutons -->
<div class="boutonsActionReferentiel">
    <div>
        <?php
        if (Autorisations::hasAutorisation(Autorisations::GAMEPLAY_GESTION_MAGIE_MODIFIER, $auth['autorisations'])) {
            echo Phalcon\Tag::SubmitButton(array("Editer", 'id' => 'editerSort', 'class' => 'bouton', 'title' => "Permet d'afficher le formulaire du sort en modification."));
        }
        ?>
    </div>
    <div>
        <?php
        echo Phalcon\Tag::SubmitButton(array("Retour", 'id' => 'retourListeSort', 'class' => 'bouton', 'title' => "Permet de retourner vers la liste des sorts."));
        ?>
    </div>
</div>

<!-- Div pour le sort -->
<div id="divFormSort" class="divReferentiel">
    <!-- En-tête -->
    <div id="divEnteteReferentiel">
        <span id="titreFormSort" class="titreReferentiel"><?php echo $sort->nom; ?></span>
    </div>

    <!-- div Contenu -->
    <div id="divContenuSort" class="divContenuReferentiel">
        <!-- Image -->
        <div id="divImageSort">
            <?php echo Phalcon\Tag::image([$sort->image, "class" => 'imageMagieConsultation']); ?>
        </div>

        <!-- Description -->
        <div class="divDescriptionMagieConsultation">
            <span id="descriptionSortConsultation"><?php echo str_replace("\n", "<br/>", $sort->description); ?></span>
        </div>

        <!-- Message RP -->
        <div class="divMessageRPMagieConsultation">
            <span id="descriptionSortMessageRP"><?php echo str_replace("\n", "<br/>", $sort->messageRP); ?></span>
        </div>

        <!-- Event Lanceur -->
        <div class="divEventLanceurMagieConsultation">
            <span id="descriptionSortEventLanceur"><?php echo str_replace("\n", "<br/>", $sort->eventLanceur); ?></span>
        </div>

        <!-- Event Global -->
        <div class="divEventGlobalMagieConsultation">
            <span id="descriptionSortEventGlobal"><?php echo str_replace("\n", "<br/>", $sort->eventGlobal); ?></span>
        </div>

        <div id="divInformationSortConsultation" class="divInformationMagie">
            <!-- Article du wiki lié -->
            <div id="divArticleSortConsultation" class="divArticleReferentiel">
                <label for="articleSortConsultation">Article du wiki </label>
                <?php if ($sort->article != null && $sort->article) { ?>
                    <a href="#" id="articleSortConsultation"
                       onclick="openPopUpWiki(<?php echo $sort->idArticle; ?>)"><?php echo $sort->article->titre; ?></a>
                <?php } else { ?>
                    <span class="texte" id="articleSortConsultation">Aucun</span>
                <?php } ?>
            </div>

            <!-- Ecole de magie -->
            <div id="divEcoleSort" class="divContenuInformationReferentiel">
                <label for="sortEcole">Ecole de magie </label>
                <?php if ($sort->ecole != null && !empty($sort->ecole)) { ?>
                    <span id="sortEcole"><?php echo $sort->ecole->nom; ?></span>
                <?php } else { ?>
                    <span id="sortEcole"> Aucune </span>
                <?php } ?>
            </div>

            <!-- Arcane -->
            <div id="divArcaneSort" class="divContenuInformationReferentiel">
                <label for="arcaneSort">Arcane </label>
                <span id="arcaneSort"><?php echo $sort->arcane; ?></span>
            </div>

            <!-- Formule Mana -->
            <div id="divManaSort" class="divContenuInformationReferentiel">
                <label for="manaSort">Mana </label>
                <span id="manaSort"><?php echo $sort->mana; ?></span>
            </div>

            <!-- Formule de la portée -->
            <div id="divPorteeSort" class="divContenuInformationReferentiel">
                <label for="porteeSort">Portée </label>
                <span id="porteeSort"><?php echo $sort->portee; ?></span>
            </div>

            <!-- Formule du coût en PA-->
            <div id="divPaSort" class="divContenuInformationReferentiel">
                <label for="paSort">Coût en PA </label>
                <span id="paSort"><?php echo $sort->coutPA; ?></span>
            </div>

            <!-- Durée du sort -->
            <div id="divDureeSort" class="divContenuInformationReferentiel">
                <label for="dureeSort">Durée du sort </label>
                <?php if (($sort->duree != null && !empty($sort->duree)) || $sort->duree == 0) { ?>
                    <span id="dureeSort"><?php echo $sort->duree; ?></span>
                <?php } else { ?>
                    <span id="dureeSort">Instantané </span>
                <?php } ?>
            </div>

            <!-- Durée maximum du sort -->
            <div id="divMaxDureeSort" class="divContenuInformationReferentiel">
                <label for="dureeMaxSort">Durée maximum du sort </label>
                <?php if (($sort->cumulDuree != null && !empty($sort->cumulDuree)) || $sort->cumulDuree == 0) { ?>
                    <span id="dureeMaxSort"><?php echo $sort->cumulDuree; ?></span>
                <?php } else { ?>
                    <span id="dureeMaxSort">Non concerné </span>
                <?php } ?>
            </div>

            <!-- Nombre d'occurence maximum du sort -->
            <div id="divCumulQuantiteSort" class="divContenuInformationReferentiel">
                <label for="cumulQuantiteSort">Nombre d'occurence maximum du sort </label>
                <?php if (($sort->cumulQuantite != null && !empty($sort->cumulQuantite)) || $sort->cumulQuantite == 0) { ?>
                    <span id="cumulQuantiteSort"><?php echo $sort->cumulQuantite; ?></span>
                <?php } else { ?>
                    <span id="cumulQuantiteSort">Non cumulable </span>
                <?php } ?>
            </div>

            <!-- Disponible utilisation bloquée -->
            <div id="divBloqueSort" class="divContenuInformationReferentiel">
                <?php
                if ($sort->isBloque) {
                    echo "<label for='isBloqueSort'>Utilisation bloquée ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isBloqueSort"]);
                } else {
                    echo "<label for='isBloqueSort'>Utilisation bloquée ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isBloqueSort"]);
                }
                ?>
            </div>

            <!-- Disponible à l'enseignement -->
            <div id="divEnseignableSort" class="divContenuInformationReferentiel">
                <?php
                if ($sort->enseignable) {
                    echo "<label for='isEnseignableSort'>Peut être enseigné ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isEnseignableSort"]);
                } else {
                    echo "<label for='isEnseignableSort'>Peut être enseigné ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isEnseignableSort"]);
                }
                ?>
            </div>

            <!-- Le sort est il esquivable -->
            <div id="divEsquivableSort" class="divContenuInformationReferentiel">
                <?php
                if ($sort->esquivable) {
                    echo "<label for='isEsquivableSort'>Peut être esquivé ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isEsquivableSort"]);
                } else {
                    echo "<label for='isEsquivableSort'>Peut être esquivé ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isEsquivableSort"]);
                }
                ?>
            </div>

            <!-- Le sort est il soumis au JS -->
            <div id="divJSSort" class="divContenuInformationReferentiel">
                <?php
                if ($sort->isJS) {
                    echo "<label for='isJSSort'>Soumis au Jet de Sauvegarde ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isJSSort"]);
                } else {
                    echo "<label for='isJSSort'>Soumis au Jet de Sauvegarde ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isJSSort"]);
                }
                ?>
            </div>

            <!-- Le sort est il soumis à une résistance vitale -->
            <div id="divJSEVSort" class="divContenuInformationReferentiel">
                <?php
                if ($sort->isJSEV) {
                    echo "<label for='isJSEVSort'>Soumis à la Résistance Vitale ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isJSEVSort"]);
                } else {
                    echo "<label for='isJSEVSort'>Soumis à la Résistance Vitale ? </label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isJSEVSort"]);
                }
                ?>
                <div class='divAide' id='divAideJSEV'
                     onMouseOver='afficherAide("Détermine si le sort peut être contré en fonction du % de vie qu&#39;à la cible.","divAideJSEV");'
                     onMouseOut='cacherAide();'></div>
            </div>

            <!-- Le sort est il retranscriptible sur un parchemin -->
            <div id="divRetranscriptibleSort" class="divContenuInformationReferentiel">
                <?php
                if ($sort->retranscriptibleSort) {
                    echo "<label for='isRetranscriptibleSort'>Peut être écrit sur un parchemin ? </label>" . Phalcon\Tag::image(["public/img/site/utils/tickVert.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isRetranscriptibleSort"]);
                } else {
                    echo "<label for='isRetranscriptibleSort'>Peut être écrit sur un parchemin ?</label>" . Phalcon\Tag::image(["public/img/site/utils/redcross.gif", "class" => 'tickcross tickcrossFormulaire', "id" => "isRetranscriptibleSort"]);
                }
                ?>
            </div>

            <!-- Table de ciblage -->
            <div id="divTableCiblageSort" class="divContenuInformationReferentiel">
                <?php
                echo Phalcon\Tag::SubmitButton(array("Table de Ciblage", 'id' => 'accesTableCiblage', 'class' => 'bouton', 'title' => "Permet d'afficher la table de ciblage du sort."));
                ?>
            </div>
        </div>

        <div id="blocParticulierNatureMagie">
            <?php echo $sort->genererDivParticulariteNatureMagie("consultation"); ?>
        </div>
    </div>

    <div id="blocInformationsTechniques">
        <!-- Bloc droit avec les différents blocs d'informations -->
        <div id="divInformationTechniqueSort">
            <div>
                <div id="divBoutonsInformationsTechniques">
                    <?php
                    echo "<div class='divBoutonsTechniquesSort'>";
                    echo "<span class='libelleBoutonTechnique'>Effets </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteEffetsSorts', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteEffetsSorts', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesSort'>";
                    echo "<span class='libelleBoutonTechnique'>Contraintes </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteContraintesSorts', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteContraintesSorts', 'class' => 'buttonHideGauche'));
                    echo "</div>";

                    echo "<div class='divBoutonsTechniquesSort'>";
                    echo "<span class='libelleBoutonTechnique'>Evolutions </span>";
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'showlisteEvolutionsSorts', 'class' => 'buttonShowDroit'));
                    echo Phalcon\Tag::SubmitButton(array("", 'id' => 'hidelisteEvolutionsSorts', 'class' => 'buttonHideGauche'));
                    echo "</div>";
                    ?>
                </div>
            </div>
        </div>
        <div id="informationTechnique" style="display:none"></div>
    </div>

</div>