<div id="LogsBlocRecherche">
    <span class="labelTitreBlocRecherche">Outils de recherche</span>
    <div id="logsType">
        <label for="selectLogType">Type </label>
        <select id="selectLogType" onchange="chargerTypeArchive();">
            <option value="0">Sélectionnez un type</option>
            <option value="MJ">Logs des MJ</option>
            <option value="ADMIN">Logs des ADMIN</option>
            <option value="DEV">Logs des DEV</option>
        </select>
    </div>
</div>